import Head from 'next/head'
import Header from '../components/Header';
import Main from '../components/Main';


export default function Home() {
  return (
    <>
      <Head>
        <title>Pkazo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>

<link rel="preconnect" href="https://fonts.gstatic.com"/>

<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet"></link>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.11.1/css/all.css"></link>
      </Head>

      
      <Header/>
      <Main/>








    </>
  )
}
